
input_number:
   dummy_temp_piscine:
     name: dummy temp input
     icon: mdi:temperature-celsius
     initial: 7
     min: -2
     max: 40
     step: 0.5

sensor:
  - platform: template
    sensors:
      pool_water_kalman:
        friendly_name: " dummy pool temp"
        value_template: >
         {{ states('input_number.dummy_temp_piscine') }}
        unit_of_measurement: "°C"

input_boolean:
  pump:
    name: "dummy pump boolean"
    

switch:
  - platform: template
    switches:
      tz3000_pompe_piscine: 
        friendly_name: "dummy pump switch"
        value_template: "{{ is_state('input_boolean.pump', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.pump
        turn_off:
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.pump
